# Generated by Django 4.0.3 on 2022-07-16 23:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(default='4.0', max_length=5)),
                ('Serie', models.CharField(blank=True, max_length=25)),
                ('Folio', models.CharField(blank=True, max_length=40)),
                ('Fecha', models.DateTimeField(blank=True)),
                ('LugarExpedicion', models.CharField(max_length=5)),
                ('NoCertificado', models.CharField(blank=True, max_length=20)),
                ('Certificado', models.TextField(blank=True)),
                ('Sello', models.TextField(blank=True)),
                ('Confirmacion', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Estado_CFDI', models.CharField(blank=True, default='NUEVO', max_length=20)),
                ('IVA', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('IVA_Ret', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ISR', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('UUID', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('Rfc_Emi', models.CharField(max_length=15)),
                ('Nombre_Emi', models.CharField(max_length=254)),
                ('RegimenFiscal_Emi', models.CharField(choices=[], max_length=4)),
                ('FacAtrAdquirente_Emi', models.CharField(blank=True, max_length=10, null=True)),
                ('Rfc_Rec', models.CharField(max_length=15)),
                ('Nombre_Rec', models.CharField(max_length=254)),
                ('RegimenFiscal_Rec', models.CharField(choices=[], max_length=4)),
                ('DomicilioFiscal_Rec', models.CharField(max_length=5)),
                ('ResidenciaFiscal_Rec', models.CharField(blank=True, choices=[], default='MEX', max_length=3)),
                ('NumRegIdTrib_Rec', models.CharField(blank=True, max_length=40, null=True)),
                ('NumPago', models.CharField(max_length=10, unique=True)),
                ('FormaPago', models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True)),
                ('TipoDeComprobante', models.CharField(default='P', max_length=3)),
                ('CondicionesDePago', models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True)),
                ('SubTotal', models.DecimalField(blank=True, decimal_places=1, default=0, editable=False, max_digits=1, null=True)),
                ('Descuento', models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True)),
                ('Moneda', models.CharField(blank=True, default='XXX', editable=False, max_length=3, null=True)),
                ('TipoCambio', models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=1, default=0, editable=False, max_digits=1, null=True)),
                ('Exportacion', models.CharField(choices=[('01', '01-No aplica'), ('02', '02-Definitiva'), ('03', '03-Temporal')], default='01', max_length=2)),
                ('MetodoPago', models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True)),
                ('FacAtrAdquirente', models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True)),
                ('UsoCFDI_Rec', models.CharField(blank=True, choices=[], default='CP01', max_length=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctoRelacionado_Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdDocumento', models.CharField(max_length=36, validators=[django.core.validators.MinLengthValidator(36)])),
                ('Serie', models.CharField(blank=True, max_length=25, validators=[django.core.validators.MinLengthValidator(1)])),
                ('Folio', models.CharField(blank=True, max_length=40, validators=[django.core.validators.MinLengthValidator(1)])),
                ('MonedaDR', models.CharField(max_length=3)),
                ('EquivalenciaDR', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('NumParcialidad', models.IntegerField()),
                ('ImpSaldoAnt', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('ImpPagado', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('ImpSaldoInsoluto', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('ObjetoImp', models.CharField(choices=[('01', '01-No objeto de impuesto.'), ('02', '02-Sí objeto de impuesto.'), ('03', '03-Sí objeto del impuesto y no obligado al desglose.')], default='02', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPago', models.DateTimeField()),
                ('FormaDePagoP', models.CharField(choices=[], max_length=2)),
                ('MonedaP', models.CharField(default='MXN', max_length=3)),
                ('TipoCambioP', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('Monto', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('RfcEmisorCtaOrd', models.CharField(blank=True, max_length=13, validators=[django.core.validators.MinLengthValidator(12)])),
                ('NomBancoOrdExt', models.CharField(blank=True, max_length=100)),
                ('CtaOrdenante', models.CharField(blank=True, max_length=50)),
                ('RfcEmisorCtaBen', models.CharField(blank=True, max_length=13, validators=[django.core.validators.MinLengthValidator(12)])),
                ('CtaBeneficiario', models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('CompPago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pagos_Rep', to='REP.comprobantepagos')),
            ],
        ),
        migrations.CreateModel(
            name='ImpuestoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Impuesto', models.CharField(choices=[('002', '002-IVA'), ('001', '001-ISR'), ('003', '003-IEPS')], max_length=3)),
                ('TipoFactor', models.CharField(blank=True, max_length=8, null=True)),
                ('TasaOCuota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('Tipo_T_R', models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('RETENCION', 'RETENCION')], max_length=10)),
                ('Pago_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REP.pagos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpuestoDR_Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Impuesto', models.CharField(choices=[('002', '002-IVA'), ('001', '001-ISR'), ('003', '003-IEPS')], max_length=3)),
                ('TipoFactor', models.CharField(blank=True, max_length=8, null=True)),
                ('TasaOCuota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('Tipo_T_R', models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('RETENCION', 'RETENCION')], max_length=10)),
                ('docto_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DR_Pagos_Impuestos', to='REP.doctorelacionado_pagos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctorelacionado_pagos',
            name='Pago_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pagos_DR', to='REP.pagos'),
        ),
        migrations.CreateModel(
            name='CfdiRelacionados_REP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoRelacion', models.CharField(choices=[], max_length=2)),
                ('UUID', models.CharField(max_length=36, unique=True)),
                ('CFDI_Rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CFDI_REL_REP', to='REP.comprobantepagos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
