# Generated by Django 4.0.3 on 2022-04-20 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctoRelacionado_Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdDocumento', models.CharField(max_length=36, validators=[django.core.validators.MinLengthValidator(36)])),
                ('Serie', models.CharField(blank=True, max_length=25, validators=[django.core.validators.MinLengthValidator(1)])),
                ('Folio', models.CharField(blank=True, max_length=40, validators=[django.core.validators.MinLengthValidator(1)])),
                ('MonedaDR', models.CharField(max_length=3)),
                ('EquivalenciaDR', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('NumParcialidad', models.IntegerField()),
                ('ImpSaldoAnt', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('ImpPagado', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('ImpSaldoInsoluto', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('ObjetoImp', models.CharField(choices=[('01', '01-No objeto de impuesto.'), ('02', '02-Sí objeto de impuesto.'), ('03', '03-Sí objeto del impuesto y no obligado al desglose.')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPago', models.DateTimeField()),
                ('FormaDePagoP', models.CharField(choices=[('1', '1-Efectivo'), ('2', '2-Cheque nominativo'), ('3', '3-Transferencia electrónica de fondos'), ('4', '4-Tarjeta de crédito'), ('5', '5-Monedero electrónico'), ('6', '6-Dinero electrónico'), ('8', '8-Vales de despensa'), ('12', '12-Dación en pago'), ('13', '13-Pago por subrogación'), ('14', '14-Pago por consignación'), ('15', '15-Condonación'), ('17', '17-Compensación'), ('23', '23-Novación'), ('24', '24-Confusión'), ('25', '25-Remisión de deuda'), ('26', '26-Prescripción o caducidad'), ('27', '27-A satisfacción del acreedor'), ('28', '28-Tarjeta de débito'), ('29', '29-Tarjeta de servicios'), ('30', '30-Aplicación de anticipos'), ('31', '31-Intermediario pagos'), ('99', '99-Por definir')], max_length=2)),
                ('MonedaP', models.CharField(default='MXN', max_length=3)),
                ('TipoCambioP', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('Monto', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('RfcEmisorCtaOrd', models.CharField(blank=True, max_length=13, validators=[django.core.validators.MinLengthValidator(12)])),
                ('NomBancoOrdExt', models.CharField(blank=True, max_length=100)),
                ('CtaOrdenante', models.CharField(blank=True, max_length=50)),
                ('RfcEmisorCtaBen', models.CharField(blank=True, max_length=13, validators=[django.core.validators.MinLengthValidator(12)])),
                ('CtaBeneficiario', models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='ImpuestoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Impuesto', models.CharField(choices=[('002', '002-IVA'), ('001', '001-ISR'), ('003', '003-IEPS')], max_length=3)),
                ('TipoFactor', models.CharField(blank=True, max_length=8, null=True)),
                ('TasaOCuota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('Tipo_T_R', models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('RETENCION', 'RETENCION')], max_length=10)),
                ('Pago_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REP.pagos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpuestoDR_Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Impuesto', models.CharField(choices=[('002', '002-IVA'), ('001', '001-ISR'), ('003', '003-IEPS')], max_length=3)),
                ('TipoFactor', models.CharField(blank=True, max_length=8, null=True)),
                ('TasaOCuota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('Tipo_T_R', models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('RETENCION', 'RETENCION')], max_length=10)),
                ('docto_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REP.doctorelacionado_pagos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctorelacionado_pagos',
            name='Pago_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REP.pagos'),
        ),
    ]
