# Generated by Django 4.0.3 on 2022-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REP', '0002_comprobantepagos_pagos_comppago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepagos',
            name='FormaPago',
            field=models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True),
        ),
    ]
