# Generated by Django 4.0.3 on 2022-04-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REP', '0003_alter_comprobantepagos_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepagos',
            name='TipoDeComprobante',
            field=models.CharField(default='P', max_length=3),
        ),
    ]
