# Generated by Django 4.0.3 on 2022-04-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REP', '0004_alter_comprobantepagos_tipodecomprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepagos',
            name='CondicionesDePago',
            field=models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantepagos',
            name='Descuento',
            field=models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantepagos',
            name='MetodoPago',
            field=models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantepagos',
            name='Moneda',
            field=models.CharField(blank=True, default='XXX', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantepagos',
            name='SubTotal',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, editable=False, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantepagos',
            name='TipoCambio',
            field=models.CharField(blank=True, default='NA', editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantepagos',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, editable=False, max_digits=1, null=True),
        ),
    ]
