# Generated by Django 4.0.3 on 2022-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REP', '0008_alter_comprobantepagos_regimenfiscal_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantepagos',
            name='NumPago',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
