# Generated by Django 4.0.3 on 2022-04-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REP', '0009_comprobantepagos_numpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantepagos',
            name='UUID',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='doctorelacionado_pagos',
            name='ObjetoImp',
            field=models.CharField(choices=[('01', '01-No objeto de impuesto.'), ('02', '02-Sí objeto de impuesto.'), ('03', '03-Sí objeto del impuesto y no obligado al desglose.')], default='02', max_length=2),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='FormaDePagoP',
            field=models.CharField(choices=[('01', '01-Efectivo'), ('02', '02-Cheque nominativo'), ('03', '03-Transferencia electrónica de fondos'), ('04', '04-Tarjeta de crédito'), ('05', '05-Monedero electrónico'), ('06', '06-Dinero electrónico'), ('08', '08-Vales de despensa'), ('12', '12-Dación en pago'), ('13', '13-Pago por subrogación'), ('14', '14-Pago por consignación'), ('15', '15-Condonación'), ('17', '17-Compensación'), ('23', '23-Novación'), ('24', '24-Confusión'), ('25', '25-Remisión de deuda'), ('26', '26-Prescripción o caducidad'), ('27', '27-A satisfacción del acreedor'), ('28', '28-Tarjeta de débito'), ('29', '29-Tarjeta de servicios'), ('30', '30-Aplicación de anticipos'), ('31', '31-Intermediario pagos'), ('99', '99-Por definir')], max_length=2),
        ),
    ]
