# Generated by Django 4.0.3 on 2022-04-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REP', '0010_comprobantepagos_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepagos',
            name='UUID',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
