# Generated by Django 4.0.3 on 2022-05-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REP', '0011_alter_comprobantepagos_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfdiRelacionados_REP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoRelacion', models.CharField(choices=[('01', '01-Nota de crédito de los documentos relacionados'), ('02', '02-Nota de débito de los documentos relacionados'), ('03', '03-Devolución de mercancía sobre facturas o traslados previos'), ('04', '04-Sustitución de los CFDI previos'), ('05', '05-Traslados de mercancías facturados previamente'), ('06', '06-Factura generada por los traslados previos'), ('07', '07-CFDI por aplicación de anticipo')], max_length=2)),
                ('UUID', models.CharField(max_length=36, unique=True)),
                ('CFDI_Rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CFDI_REL_REP', to='REP.comprobantepagos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
