# Generated by Django 4.0.3 on 2022-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatSat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_regimenfiscal',
            name='Fisica',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='c_regimenfiscal',
            name='Moral',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
