# Generated by Django 4.0.3 on 2022-04-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatSat', '0002_alter_c_regimenfiscal_fisica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_TipoRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relacion', models.CharField(max_length=2)),
                ('Descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
