# Generated by Django 4.0.3 on 2022-05-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatSat', '0004_alter_c_claveunidad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_estado',
            name='Nombre_estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
