# Generated by Django 4.0.3 on 2022-05-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatSat', '0005_alter_c_estado_nombre_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_moneda',
            name='Descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
