# Generated by Django 4.0.3 on 2022-05-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatSat', '0007_alter_c_regimenfiscal_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_usocfdi',
            name='Descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
