# Generated by Django 4.0.3 on 2022-04-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionAduanera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroPedimento', models.CharField(max_length=21, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionGlobal_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodicidad', models.CharField(max_length=4)),
                ('Meses', models.CharField(max_length=2)),
                ('Año', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(default='4.0', max_length=5)),
                ('Serie', models.CharField(blank=True, max_length=25)),
                ('Folio', models.CharField(blank=True, max_length=40)),
                ('Fecha', models.DateTimeField(blank=True)),
                ('TipoCambio', models.FloatField(blank=True, null=True)),
                ('Moneda', models.CharField(default='MXN', max_length=3)),
                ('Exportacion', models.CharField(choices=[('01', '01-No aplica'), ('02', '02-Definitiva'), ('03', '03-Temporal')], default='01', max_length=2)),
                ('MetodoPago', models.CharField(blank=True, choices=[('PUE', 'PUE-Pago en una sola exhibición'), ('PPD', 'PPD-Pago en parcialidades o diferido')], default='PPD', max_length=4, null=True)),
                ('LugarExpedicion', models.CharField(max_length=5)),
                ('TipoDeComprobante', models.CharField(default='I', max_length=3)),
                ('NoCertificado', models.CharField(blank=True, max_length=20)),
                ('Certificado', models.TextField(blank=True)),
                ('Sello', models.TextField(blank=True)),
                ('SubTotal', models.FloatField(blank=True, null=True)),
                ('Descuento', models.FloatField(blank=True, null=True)),
                ('CondicionesDePago', models.CharField(blank=True, max_length=1000, null=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('Confirmacion', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Estado_CFDI', models.CharField(blank=True, max_length=20)),
                ('Rfc_Emi', models.CharField(max_length=15)),
                ('Nombre_Emi', models.CharField(max_length=254)),
                ('RegimenFiscal_Emi', models.CharField(max_length=4)),
                ('FacAtrAdquirente_Emi', models.CharField(blank=True, max_length=10, null=True)),
                ('Rfc_Rec', models.CharField(max_length=15)),
                ('Nombre_Rec', models.CharField(max_length=254)),
                ('RegimenFiscal_Rec', models.CharField(max_length=4)),
                ('DomicilioFiscal_Rec', models.CharField(max_length=5)),
                ('ResidenciaFiscal_Rec', models.CharField(max_length=4)),
                ('NumRegIdTrib_Rec', models.CharField(max_length=40)),
                ('UsoCFDI_Rec', models.CharField(max_length=4)),
                ('Ingreso', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingreso_Conceptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaveProdServ', models.CharField(max_length=8)),
                ('NoIdentificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('Cantidad', models.DecimalField(decimal_places=6, max_digits=15)),
                ('ClaveUnidad', models.CharField(max_length=4)),
                ('Unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=1000)),
                ('ValorUnitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=18)),
                ('Descuento', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ObjetoImp', models.CharField(choices=[('01', '01-No objeto de impuesto.'), ('02', '02-Sí objeto de impuesto.'), ('03', '03-Sí objeto del impuesto y no obligado al desglose.')], default='02', max_length=2)),
                ('IVA', models.BooleanField(default=False)),
                ('ISR', models.BooleanField(default=False)),
                ('IVA_Ret', models.BooleanField(default=False)),
                ('Comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comp.ingreso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaveProdServ', models.CharField(max_length=8)),
                ('NoIdentificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('Cantidad', models.DecimalField(decimal_places=6, max_digits=15)),
                ('ClaveUnidad', models.CharField(max_length=4)),
                ('Unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=1000)),
                ('ValorUnitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=18)),
                ('InfoAduanera', models.ManyToManyField(blank=True, related_name='Parte_InfoAduana', to='Comp.informacionaduanera')),
                ('Ingreso_Concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IngresoConcepto_Parte', to='Comp.ingreso_conceptos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Impuesto_PartidasIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Impuesto', models.CharField(choices=[('002', '002-IVA'), ('001', '001-ISR'), ('003', '003-IEPS')], max_length=3)),
                ('TipoFactor', models.CharField(blank=True, max_length=8, null=True)),
                ('TasaOCuota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('Tipo_T_R', models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('RETENCION', 'RETENCION')], max_length=10)),
                ('Imp_Partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comp.ingreso_conceptos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Impuesto_Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Base', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Impuesto', models.CharField(choices=[('002', '002-IVA'), ('001', '001-ISR'), ('003', '003-IEPS')], max_length=3)),
                ('TipoFactor', models.CharField(blank=True, max_length=8, null=True)),
                ('TasaOCuota', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('Tipo_T_R', models.CharField(choices=[('TRASLADO', 'TRASLADO'), ('RETENCION', 'RETENCION')], max_length=10)),
                ('ImpuestosIngreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Impuestos_Ingreso', to='Comp.ingreso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaPredial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=150)),
                ('Ingreso_Concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IngresoConcepto_CtaPredial', to='Comp.ingreso_conceptos')),
            ],
        ),
        migrations.CreateModel(
            name='CfdiRelacionados_Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoRelacion', models.CharField(max_length=3)),
                ('UUID', models.CharField(max_length=36)),
                ('CFDI_Rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CFDI_REL_Comprobante', to='Comp.ingreso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ACuentaTerceros_Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RfcACuentaTerceros', models.CharField(max_length=15)),
                ('NombreACuentaTerceros', models.CharField(max_length=254)),
                ('RegimenFiscalACuentaTerceros', models.CharField(max_length=3)),
                ('DomicilioFiscalACuentaTerceros', models.CharField(max_length=5)),
                ('Ingreso_Concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingreso_Concepto_ACT', to='Comp.ingreso_conceptos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformacionGlobal_Ingreso',
            fields=[
                ('informacionglobal_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Comp.informacionglobal_base')),
                ('Ingreso_InfoGlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingreso_InfoGlobal', to='Comp.ingreso')),
            ],
            bases=('Comp.informacionglobal_base',),
        ),
    ]
