# Generated by Django 4.0.3 on 2022-04-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='FormaPago',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True),
        ),
    ]
