# Generated by Django 4.0.3 on 2022-04-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0002_ingreso_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='FormaPago',
            field=models.CharField(blank=True, choices=[('1', '1-Efectivo'), ('2', '2-Cheque nominativo'), ('3', '3-Transferencia electrónica de fondos'), ('4', '4-Tarjeta de crédito'), ('5', '5-Monedero electrónico'), ('6', '6-Dinero electrónico'), ('8', '8-Vales de despensa'), ('12', '12-Dación en pago'), ('13', '13-Pago por subrogación'), ('14', '14-Pago por consignación'), ('15', '15-Condonación'), ('17', '17-Compensación'), ('23', '23-Novación'), ('24', '24-Confusión'), ('25', '25-Remisión de deuda'), ('26', '26-Prescripción o caducidad'), ('27', '27-A satisfacción del acreedor'), ('28', '28-Tarjeta de débito'), ('29', '29-Tarjeta de servicios'), ('30', '30-Aplicación de anticipos'), ('31', '31-Intermediario pagos'), ('99', '99-Por definir')], max_length=2, null=True),
        ),
    ]
