# Generated by Django 4.0.3 on 2022-04-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0003_alter_ingreso_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='Estado_CFDI',
            field=models.CharField(blank=True, default='NUEVO', max_length=20),
        ),
    ]
