# Generated by Django 4.0.3 on 2022-04-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0004_alter_ingreso_estado_cfdi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfdirelacionados_ingreso',
            name='TipoRelacion',
            field=models.CharField(choices=[], max_length=2),
        ),
    ]
