# Generated by Django 4.0.3 on 2022-04-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0005_alter_cfdirelacionados_ingreso_tiporelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfdirelacionados_ingreso',
            name='TipoRelacion',
            field=models.CharField(choices=[('01', '01-Nota de crédito de los documentos relacionados'), ('02', '02-Nota de débito de los documentos relacionados'), ('03', '03-Devolución de mercancía sobre facturas o traslados previos'), ('04', '04-Sustitución de los CFDI previos'), ('05', '05-Traslados de mercancías facturados previamente'), ('06', '06-Factura generada por los traslados previos'), ('07', '07-CFDI por aplicación de anticipo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='NumRegIdTrib_Rec',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso_conceptos',
            name='ObjetoImp',
            field=models.CharField(choices=[('01', '01-No objeto de impuesto.'), ('02', '02-Sí objeto de impuesto.'), ('03', '03-Sí objeto del impuesto y no obligado al desglose.')], max_length=2),
        ),
    ]
