# Generated by Django 4.0.3 on 2022-04-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0006_alter_cfdirelacionados_ingreso_tiporelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfdirelacionados_ingreso',
            name='UUID',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
