# Generated by Django 4.0.3 on 2022-04-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0007_alter_cfdirelacionados_ingreso_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='ISR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='IVA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='IVA_Ret',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
