# Generated by Django 4.0.3 on 2022-04-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0008_ingreso_isr_ingreso_iva_ingreso_iva_ret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='Descuento',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='ISR',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='IVA',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='IVA_Ret',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='SubTotal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='TipoCambio',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='Total',
            field=models.DecimalField(decimal_places=6, max_digits=21, null=True),
        ),
    ]
