# Generated by Django 4.0.3 on 2022-04-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comp', '0012_alter_ingreso_residenciafiscal_rec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='UUID',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='FormaPago',
            field=models.CharField(blank=True, choices=[('01', '01-Efectivo'), ('02', '02-Cheque nominativo'), ('03', '03-Transferencia electrónica de fondos'), ('04', '04-Tarjeta de crédito'), ('05', '05-Monedero electrónico'), ('06', '06-Dinero electrónico'), ('08', '08-Vales de despensa'), ('12', '12-Dación en pago'), ('13', '13-Pago por subrogación'), ('14', '14-Pago por consignación'), ('15', '15-Condonación'), ('17', '17-Compensación'), ('23', '23-Novación'), ('24', '24-Confusión'), ('25', '25-Remisión de deuda'), ('26', '26-Prescripción o caducidad'), ('27', '27-A satisfacción del acreedor'), ('28', '28-Tarjeta de débito'), ('29', '29-Tarjeta de servicios'), ('30', '30-Aplicación de anticipos'), ('31', '31-Intermediario pagos'), ('99', '99-Por definir')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='UsoCFDI_Rec',
            field=models.CharField(blank=True, choices=[('G01', 'G01-Adquisiciï¿½n de mercancï¿½as.'), ('G02', 'G02-Devoluciones, descuentos o bonificaciones.'), ('G03', 'G03-Gastos en general.'), ('I01', 'I01-Construcciones.'), ('I02', 'I02-Mobiliario y equipo de oficina por inversiones.'), ('I03', 'I03-Equipo de transporte.'), ('I04', 'I04-Equipo de computo y accesorios.'), ('I05', 'I05-Dados, troqueles, moldes, matrices y herramental.'), ('I06', 'I06-Comunicaciones telefï¿½nicas.'), ('I07', 'I07-Comunicaciones satelitales.'), ('I08', 'I08-Otra maquinaria y equipo.'), ('D01', 'D01-Honorarios mï¿½dicos, dentales y gastos hospitalarios.'), ('D02', 'D02-Gastos mï¿½dicos por incapacidad o discapacidad.'), ('D03', 'D03-Gastos funerales.'), ('D04', 'D04-Donativos.'), ('D05', 'D05-Intereses reales efectivamente pagados por crï¿½ditos hipotecarios (casa habitaciï¿½n).'), ('D06', 'D06-Aportaciones voluntarias al SAR.'), ('D07', 'D07-Primas por seguros de gastos mï¿½dicos.'), ('D08', 'D08-Gastos de transportaciï¿½n escolar obligatoria.'), ('D09', 'D09-Depï¿½sitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.'), ('D10', 'D10-Pagos por servicios educativos (colegiaturas).'), ('S01', 'S01-Sin efectos fiscales.  '), ('CP01', 'CP01-Pagos'), ('CN01', 'CN01-Nï¿½mina')], max_length=4, null=True),
        ),
    ]
