# Generated by Django 4.0.3 on 2022-04-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=8, unique=True)),
                ('RFC', models.CharField(max_length=13, unique=True)),
                ('Nombre', models.CharField(max_length=255)),
                ('Regimen', models.CharField(max_length=3)),
                ('Domicilio', models.CharField(max_length=5)),
                ('Recidencia', models.CharField(max_length=3)),
                ('Tax_id', models.CharField(blank=True, max_length=12)),
                ('Uso_CFDI', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=8, unique=True)),
                ('RFC', models.CharField(max_length=13, unique=True)),
                ('Nombre', models.CharField(max_length=255)),
                ('Regimen', models.CharField(max_length=3)),
                ('Domicilio', models.CharField(max_length=5)),
                ('Num_Certificado', models.CharField(blank=True, max_length=55, null=True)),
                ('IVA', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('IVA_Ret', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('ISR', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
            ],
        ),
    ]
