# Generated by Django 4.0.3 on 2022-04-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='Recidencia',
            field=models.CharField(choices=[], default='MEX', max_length=3),
        ),
    ]
