# Generated by Django 4.0.3 on 2022-04-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_alter_cliente_recidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaveProducto', models.CharField(max_length=8)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Unidad', models.CharField(max_length=5)),
                ('ValorUnitario', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('IVA', models.BooleanField(default=False)),
                ('IVA_Ret', models.BooleanField(default=False)),
                ('ISR', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Regimen',
            field=models.CharField(choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 - Arrendamiento'), ('607', '607 - Régimen de Enajenación o Adquisición de Bienes'), ('608', '608 - Demás ingresos'), ('610', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', '611 - Ingresos por Dividendos (socios y accionistas)'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('614', '614 - Ingresos por intereses'), ('615', '615 - Régimen de los ingresos por obtención de premios'), ('616', '616 - Sin obligaciones fiscales'), ('620', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', '621 - Incorporación Fiscal'), ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('623', '623 - Opcional para Grupos de Sociedades'), ('624', '624 - Coordinados'), ('625', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', '626 - Régimen Simplificado de Confianza')], max_length=3),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Regimen',
            field=models.CharField(choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 - Arrendamiento'), ('607', '607 - Régimen de Enajenación o Adquisición de Bienes'), ('608', '608 - Demás ingresos'), ('610', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', '611 - Ingresos por Dividendos (socios y accionistas)'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('614', '614 - Ingresos por intereses'), ('615', '615 - Régimen de los ingresos por obtención de premios'), ('616', '616 - Sin obligaciones fiscales'), ('620', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', '621 - Incorporación Fiscal'), ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('623', '623 - Opcional para Grupos de Sociedades'), ('624', '624 - Coordinados'), ('625', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', '626 - Régimen Simplificado de Confianza')], max_length=3),
        ),
    ]
