# Generated by Django 4.0.3 on 2022-04-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_producto_alter_cliente_regimen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ClaveInterna',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
