# Generated by Django 4.0.3 on 2022-04-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_producto_claveinterna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ClaveInterna',
            field=models.CharField(max_length=10),
        ),
    ]
