# Generated by Django 4.0.3 on 2022-04-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_alter_producto_isr_alter_producto_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ValorUnitario',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
