# Generated by Django 4.0.3 on 2022-04-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_alter_producto_valorunitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ClaveInterna',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ISR',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='IVA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='IVA_Ret',
            field=models.BooleanField(default=False),
        ),
    ]
