# Generated by Django 4.0.3 on 2022-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0010_alter_producto_claveinterna_alter_producto_isr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Recidencia',
            field=models.CharField(default='MEX', max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Regimen',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Recidencia',
            field=models.CharField(default='MEX', max_length=3),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Regimen',
            field=models.CharField(max_length=3),
        ),
    ]
